strana = float(input("Zadaj veľkosť strany kocky: "))
stenova = strana * 2 ** (1/2)
telesova = strana * 3 ** (1/2)
print("Stenová uhlopriečka je: ", round(stenova, 2))
print("Telesová uhlopriečka je: ", round(telesova, 2))